ifndef::env-github[:icons: font]
:toc: preamble
:toclevels: 2
:sectanchors:

ifdef::env-github[]
++++
<a id="readme-top"></a>
<div align="center">
<a href="https://github.com/dev-centr/infra-template/graphs/contributors"><img src="https://img.shields.io/github/contributors/dev-centr/infra-template.svg?style=for-the-badge" alt="Contributors"></a>
<a href="https://github.com/dev-centr/infra-template/network/members"><img src="https://img.shields.io/github/forks/dev-centr/infra-template.svg?style=for-the-badge" alt="Forks"></a>
<a href="https://github.com/dev-centr/infra-template/stargazers"><img src="https://img.shields.io/github/stars/dev-centr/infra-template.svg?style=for-the-badge" alt="Stars"></a>
<a href="https://github.com/dev-centr/infra-template/issues"><img src="https://img.shields.io/github/issues/dev-centr/infra-template.svg?style=for-the-badge" alt="Issues"></a>
<br />
<h3 align="center">Org infra template</h3>
<p align="center">
Reusable Pulumi + Antora skeleton for org infra repos.<br /><br />
<a href="https://github.com/dev-centr/infra-template/issues">Report Bug</a>
&middot;
<a href="https://github.com/dev-centr/infra-template/issues">Request Feature</a>
</p>
</div>
++++
endif::[]

ifndef::env-github[]
image:https://img.shields.io/github/contributors/dev-centr/infra-template.svg?style=for-the-badge[Contributors,link=https://github.com/dev-centr/infra-template/graphs/contributors]
image:https://img.shields.io/github/forks/dev-centr/infra-template.svg?style=for-the-badge[Forks,link=https://github.com/dev-centr/infra-template/network/members]
image:https://img.shields.io/github/stars/dev-centr/infra-template.svg?style=for-the-badge[Stars,link=https://github.com/dev-centr/infra-template/stargazers]
image:https://img.shields.io/github/issues/dev-centr/infra-template.svg?style=for-the-badge[Issues,link=https://github.com/dev-centr/infra-template/issues]

= Org infra template

Reusable Pulumi + Antora skeleton for org infra repos.

link:https://github.com/dev-centr/infra-template/issues[Report Bug] ·
link:https://github.com/dev-centr/infra-template/issues[Request Feature]
endif::[]

== About The Project

Reusable Pulumi (TypeScript) + Antora docs skeleton for a GitHub organization's central `infra` repository.

Copy or use as the source when DevCentr bootstraps an org-level infrastructure repo.

=== Layout

----
Pulumi.yaml
package.json
tsconfig.json
src/index.ts
docs/
README.adoc
.gitignore
----

Strategic email/vendor choices: link:https://github.com/dev-centr/business-bootstrap[business-bootstrap].

link:#readme-top[back to top]

== Installation

Copy this template into your org's `infra` repository, then:

[source,bash]
----
pnpm install
pulumi up
----

link:#readme-top[back to top]

== Contact

DevCentr.org — support@devcentr.org

* Project: https://github.com/dev-centr/infra-template
* Site: https://devcentr.org

link:#readme-top[back to top]
